// @mandaitor/taxonomy-core — Taxonomy Manifest types
//
// These types define the schema for the taxonomy-manifest.json artifact
// generated by scripts/generate-manifest.mjs. The manifest is consumed by
// the Mandaitor backend to dynamically validate taxonomy references in
// widget configurations.

/**
 * A single entry in the taxonomy manifest, describing one validated taxonomy.
 */
export interface TaxonomyManifestEntry {
  /** npm package name, e.g. "@mandaitor/taxonomy-construction" */
  package: string;
  /** Taxonomy ID matching TaxonomyMetadata.id */
  taxonomyId: string;
  /** Semantic version */
  version: string;
  /** Human-readable name */
  name: string;
  /** Brief description */
  description: string;
  /** Display name for UI */
  displayName: string;
  /** Industry verticals covered */
  verticals: string[];
  /** License identifier (SPDX) */
  license: string;
  /** Minimum @mandaitor/taxonomy-core version required */
  coreVersion: string;
  /** Number of actions defined */
  actionsCount: number;
  /** Number of resource patterns defined */
  resourcesCount: number;
  /** Number of constraint templates defined */
  constraintsCount: number;
  /** Number of mandate templates defined */
  templatesCount: number;
  /** Distribution of actions by risk level */
  riskDistribution: Partial<Record<"LOW" | "MEDIUM" | "HIGH" | "CRITICAL", number>>;
  /** Tags for filtering and categorization */
  tags: string[];
}

/**
 * The complete taxonomy manifest file schema.
 */
export interface TaxonomyManifest {
  /** Schema version for forward compatibility */
  schema_version: string;
  /** ISO 8601 timestamp of generation */
  generated_at: string;
  /** Number of taxonomies in the manifest */
  taxonomy_count: number;
  /** All validated taxonomy entries */
  taxonomies: TaxonomyManifestEntry[];
}
